const data = [
  {
    name: 'Dal Fry',
    price: 140,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Amul Dal Fry',
    price: 150,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Dal Makhani',
    price: 210,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Moong Dal Fry',
    price: 140,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Jeera Chawal',
    price: 140,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Singapuri Fried Rice',
    price: 190,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Stuffed Naan (1 Pc)',
    price: 90,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Plain Roti (1 Pc)',
    price: 15,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Missi Pyaj Roti',
    price: 45,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Butter Roti',
    price: 20,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Pyaj Roti',
    price: 40,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Pyaj Naan',
    price: 100,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Missi Roti',
    price: 40,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Lachha Paratha',
    price: 55,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Butter Naan',
    price: 65,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Tiranga Naan',
    price: 65,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Paneer Paratha',
    price: 90,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Thali',
    price: 180,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Special Thali',
    price: 280,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Kadhi Pakoda',
    price: 140,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Besan Gatta',
    price: 140,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Aloo Jeera',
    price: 160,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Malai Kofta',
    price: 260,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Aloo Matar',
    price: 160,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Mix Veg',
    price: 240,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Chana Masala',
    price: 240,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Aloo Chhole',
    price: 160,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Sev Bhaji',
    price: 200,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Dahi Plain',
    price: 80,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Boondi Raita',
    price: 110,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Mix Raita',
    price: 120,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Mineral Water (1 ltr)',
    price: 40,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Matar Paneer',
    price: 240,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Paneer Bhurji',
    price: 290,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Chhole Paneer',
    price: 240,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Palak Paneer',
    price: 239,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Malai Paneer',
    price: 280,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Kadai Paneer',
    price: 280,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Cheese Tomato',
    price: 240,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Gravy Chap',
    price: 280,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Shahi Paneer',
    price: 280,
    is_veg: true,
    category: 'Recommended',
  },
  {
    name: 'Dal Fry',
    price: 140,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Amul Dal Fry',
    price: 150,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Dal Makhani',
    price: 210,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Dal Makhani Punjabi Tadka',
    price: 230,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Moong Dal Fry',
    price: 140,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Special Dal Tadka',
    price: 180,
    is_veg: true,
    category: 'Main_Course',
  },
  {
    name: 'Plain Chawal',
    price: 110,
    is_veg: true,
    category: 'Chawal___Biryani',
  },
  {
    name: 'Jeera Chawal',
    price: 140,
    is_veg: true,
    category: 'Chawal___Biryani',
  },
  {
    name: 'Fry Chawal',
    price: 180,
    is_veg: true,
    category: 'Chawal___Biryani',
  },
  {
    name: 'Chinese Fry Rice',
    price: 190,
    is_veg: true,
    category: 'Chawal___Biryani',
  },
  {
    name: 'Singapuri Fried Rice',
    price: 190,
    is_veg: true,
    category: 'Chawal___Biryani',
  },
  {
    name: 'Stuffed Naan (1 Pc)',
    price: 90,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Plain Roti (1 Pc)',
    price: 15,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Amul Butter Roti',
    price: 25,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Missi Pyaj Roti',
    price: 45,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Butter Roti',
    price: 20,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Pyaj Roti',
    price: 40,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Pyaj Naan',
    price: 100,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Missi Roti',
    price: 40,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Lachha Paratha',
    price: 55,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Butter Naan',
    price: 65,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Tiranga Naan',
    price: 65,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Paneer Paratha',
    price: 90,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Paneer Naan',
    price: 100,
    is_veg: true,
    category: 'Tandoori_Khazana',
  },
  {
    name: 'Deluxe Thali',
    price: 350,
    is_veg: true,
    category: 'Thali',
  },
  {
    name: 'Thali',
    price: 180,
    is_veg: true,
    category: 'Thali',
  },
  {
    name: 'Special Thali',
    price: 280,
    is_veg: true,
    category: 'Thali',
  },
  {
    name: 'Kadhi Pakoda',
    price: 140,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Besan Gatta',
    price: 140,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Aloo Jeera',
    price: 160,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Baingan Bharta',
    price: 160,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Malai Kofta',
    price: 260,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Aloo Matar',
    price: 160,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Mix Veg',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Chana Masala',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Matar  masala',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Dahi Fry',
    price: 160,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Aloo Chhole',
    price: 160,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Aloo Palak',
    price: 180,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Sev Bhaji',
    price: 200,
    is_veg: true,
    category: 'Lamb_Shahi_Sabjiya',
  },
  {
    name: 'Dahi Plain',
    price: 80,
    is_veg: true,
    category: 'Dahi',
  },
  {
    name: 'Boondi Raita',
    price: 110,
    is_veg: true,
    category: 'Dahi',
  },
  {
    name: 'Mix Raita',
    price: 120,
    is_veg: true,
    category: 'Dahi',
  },
  {
    name: 'Green salad',
    price: 60,
    is_veg: true,
    category: 'Salad',
  },
  {
    name: 'Papad',
    price: 19,
    is_veg: true,
    category: 'Salad',
  },
  {
    name: 'Papad.',
    price: 30,
    is_veg: true,
    category: 'Snacks',
  },
  {
    name: 'Mineral Water (1 ltr)',
    price: 40,
    is_veg: true,
    category: 'Beverages',
  },
  {
    name: 'Matar Paneer',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Paneer Bhurji',
    price: 290,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Chhole Paneer',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Palak Paneer',
    price: 239,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Malai Paneer',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Paneer Butter Masala',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Kadai Paneer',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Cheese Tomato',
    price: 240,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Gravy Chap',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Kadhai Chap Gravy',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Cream Chap Gravy',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Shahi Paneer',
    price: 280,
    is_veg: true,
    category: 'Lamb_Shahi_Paneer',
  },
  {
    name: 'Aloo pratha',
    price: 55,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Gobhi Pratha',
    price: 55,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Lacha pratha',
    price: 55,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Paneer pratha',
    price: 79,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Kulcha Naan',
    price: 85,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Gud Pratha',
    price: 65,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Chini pratha',
    price: 55,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Green chilli roti',
    price: 45,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Tiranga pratha',
    price: 55,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: "Chilli lacha pratha'",
    price: 65,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Tiranga naan Special',
    price: 100,
    is_veg: true,
    category: 'Breads',
  },
  {
    name: 'Chillli Naan',
    price: 100,
    is_veg: true,
    category: 'Breads',
  },
]
export default data
